branches:
  only:
    - master

environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3

# We always use a 64-bit machine, but can build x86 distributions
platform:
    - x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
  - pip install --upgrade setuptools
  - pip install pytest
  - pip install pytest-cov pytest
  - pip install codecov
  - pip install coveralls
  - pip install pytest-xdist
  - pip install codacy-coverage
  - pip install matplotlib
  - pip install -r requirements.txt

test_script:
  - pytest --cache-clear -n 8 -q --cov=./ || --force-yes
